name: decoration
version: '${version}'
main: decoration.decoration.Decoration
api-version: 1.19

commands:
  decoration-list:
    description: 칭호 리스트 보기
    aliases:
      - 칭호보기

  decoration-modify:
    description: 칭호 변경하기
    aliases:
      - 칭호변경


